server:
  port: 4444

spring:
  application:
    name: zuul-server

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 5


zuul:
  ignored-services: "*"
  routes:
    account-service:
      service-id: ACCOUNT-SERVICE
      path: /account/**
    booking-service:
      service-id: BOOKING-SERVICE
      path: /booking/**
    auth-service:
      service-id: AUTH-SERVICE
      path: /auth/**
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
