spring:
  application:
    name: auth-service
server:
  port: 5555

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 5