# Spring properties
spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:h2:file:~/db/booking
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

#    jpa:
#      hibernate:
#        ddl-auto: update

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port